FROM gradle:8.7-jdk21 AS build
WORKDIR /app
COPY build.gradle.kts ./
COPY --chown=gradle:gradle . .
RUN gradle dependencies --refresh-dependencies \
 && gradle clean build -x test --no-daemon

FROM openjdk:21-jdk-slim
WORKDIR /app
COPY --from=build /app/build/libs/*.jar app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]