spring:
  datasource:
    url: jdbc:postgresql://db:5432/files_db
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

file:
  storage:
    location: /data/files

springdoc:
  api-docs.path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

server:
  port: 8080
